name: Check TDLib

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  schedule:
    - cron: "0 * * * *"

  # Run tests for any PRs.
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get TDLib last commit id
        run: |
          wget --header="Accept: application/vnd.github.VERSION.sha" -qO tdlib_commit_id  https://api.github.com/repos/tdlib/td/commits/master

      - name: Check TDLib last commit ID
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        run: |
          if [[ "$(<tdlib_commit_id)" == "$(<last_tdlib_commit_id)" ]]; then
            cat tdlib_commit_id > last_tdlib_commit_id
            git add last_tdlib_commit_id
            git commit -c user.name="GitHub Actions" -c user.email="actions@github.com" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" -m "Update TDLib last commit ID"
            git push
          fi
