name: Docker

on:
  push:
    branches:
      - main

    tags:
      - v*

  schedule:
    - cron: "0 * * * *"

env:
  IMAGE_NAME: polaris-base

jobs:
  check:
    outputs:
      update: ${{ steps.check.outputs.update }}
      commit_id: ${{ steps.check.outputs.commit_id }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get TDLib last commit id
        run: |
          wget --header="Accept: application/vnd.github.VERSION.sha" -qO tdlib_commit_id  $GITHUB_API_URL/repos/tdlib/td/commits/master
          
      - name: Get short commit id
        run: git rev-parse --short "$(<tdlib_commit_id)" > tdlib_commit_id

      - name: Check if commit ID is different
        id: check
        run: |
          if [[ "$(<tdlib_commit_id)" != "$(<TDLib)" ]]; then
            echo "::set-output name=update::1"
            echo "::set-output name=commit_id::$(<tdlib_commit_id)"
          else
            echo "::set-output name=update::0"
          fi

  update:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.update == 1

    steps:
      - uses: actions/checkout@v2

      - name: Update TDLib commit ID
        run: echo "${{ needs.check.outputs.commit_id }}" > TDLib
      - name: Create commit
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git add TDLib
          git -c user.name="GitHub Actions" -c user.email="actions@github.com" commit --allow-empty -m "Update TDLib last commit ID" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git push
          
      - name: Generate artifact for TDLib file
        uses: actions/upload-artifact@v2
        with:
          name: TDLib
          path: TDLib

  push:
    runs-on: ubuntu-latest
    needs: update

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          COMMIT=$(<TDLib)

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION $IMAGE_NAME $IMAGE_ID:$COMMIT
          docker push $IMAGE_ID:$COMMIT
